server:
  port: 9527

zuul:
  routes:
    system:
      path: /system/** #路由匹配的路径
      service-id: SYSTEM-SERVICE
    course:
      path: /course/**
      service-id: COURSE-SERVICE
    file:
      path: /file/**
      service-id: FILEUPLOAD-SERVICE
    page:
      path: /page/**
      service-id: PAGE-SERVICE
    user:
      path: /user/**
      service-id: USER-SERVICE
  ignored-services: "*"
  prefix: /services

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

spring:
  application:
    name: ZUUL-GETEWAR