server:
  port: 9008


spring:
  application:
    name: USER-SERVICE
  datasource:
    url: jdbc:mysql:///hrm-user?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=utf8

hrm:
  swagger:
    title: 用户中心
    description: 用户中心接口文档